Repository GOCDB/gocdb, pull requests merged in 2022-09, with the labels that each got.

#368 Refactor API Auth to support non X.509 identifiers
  htdocs/PI/index.php
  lib/Gocdb_Services/APIAuthenticationService.php
  tests/unit/lib/Gocdb_Services/APIAuthenticationServiceTest.php
Labels: enhancement

#380 Re-add authByAnyCert/Identifier method
  htdocs/PI/index.php
Labels: bug

#150 Modified scope handling.
  config/gocdb_schema.xml
  config/local_info.xml
  htdocs/web_portal/controllers/admin/edit_scope.php
  htdocs/web_portal/controllers/scope.php
  htdocs/web_portal/controllers/utils.php
  htdocs/web_portal/css/web_portal.php
  htdocs/web_portal/views/admin/add_scope.php
  htdocs/web_portal/views/admin/edit_scope.php
  htdocs/web_portal/views/admin/edited_scope.php
  htdocs/web_portal/views/scope.php
  htdocs/web_portal/views/scopes.php
  lib/Doctrine/deploy/AddScopes.php
  lib/Doctrine/deploy/sampleData/Scopes.xml
  lib/Doctrine/entities/Scope.php
  lib/Gocdb_Services/Config.php
  lib/Gocdb_Services/Scope.php
  tests/unit/lib/Gocdb_Services/ScopeServiceTest.php
Labels: enhancement, schema change
