Repository GOCDB/gocdb, pull requests merged in 2023-02, with the labels that each got.

#274 Update Oracle import instructions.
  INSTALL.md
Labels: enhancement

#421 Code standards for multiple API auth credentials with same identifier
  htdocs/PI/index.php
  lib/Gocdb_Services/APIAuthenticationService.php
  tests/DoctrineTestSuite1.php
  tests/unit/lib/Gocdb_Services/APIAuthenticationServiceTest.php
Labels: enhancement

#304 Unaccentuate "unaccentuated"
  htdocs/web_portal/views/user/edit_user.php
  htdocs/web_portal/views/user/register.php
Labels: enhancement

#393 373 deploying the sample data fails
  lib/Doctrine/deploy/AddServiceGroups.php
Labels: bug

#425 Fix out of date link in manage roles page
  htdocs/web_portal/views/political_role/view_requests.php
Labels: enhancement

#426 Add iris.ac.uk logo images for NGI entity
  htdocs/web_portal/img/ngi/fullSize/iris.ac.uk.jpg
  htdocs/web_portal/img/ngi/iris.ac.uk.jpg
Labels: enhancement

#353 Update sponsor logos and text
  README.md
  htdocs/images/egi_logo.jpg
  htdocs/images/eosc-hub-v-web_150.png
  htdocs/images/flags/eu.png
  htdocs/images/logos/egi.png
  htdocs/images/logos/eosc_future.png
  htdocs/images/logos/iris_ac_uk.png
  htdocs/images/logos/ukri_stfc.png
  htdocs/images/logos/ukri_stfc_with_text.png
  htdocs/landing/home.css
  htdocs/landing/index.php
  htdocs/web_portal/components/Draw_Components/draw_page_components.php
  htdocs/web_portal/css/web_portal.php
Labels: enhancement

#429 Remove type from uniqueness check
  lib/Gocdb_Services/APIAuthenticationService.php
  lib/Gocdb_Services/Site.php
Labels: enhancement

#370 Include NGI role in revocation evaluation for orphaned API credentials
  htdocs/web_portal/controllers/user/view_user.php
  htdocs/web_portal/views/user/view_user.php
  lib/Gocdb_Services/Role.php
  tests/unit/lib/Gocdb_Services/RoleServiceTest2.php
Labels: enhancement

#356 hotfix for moment.js library to master branch
  htdocs/web_portal/javascript/moment/moment-with-locales.min.js
  htdocs/web_portal/static_html/goc5_logo.html
  htdocs/web_portal/static_php/standard_header.php
Labels: enhancement, hotfix

#355 Hotfix-update-momentdotjs to dev branch
  htdocs/web_portal/javascript/moment/moment-with-locales.min.js
  htdocs/web_portal/static_html/goc5_logo.html
  htdocs/web_portal/static_php/standard_header.php
Labels: enhancement, hotfix

#432 Remove "IRIS IAM" login button from landing page
  htdocs/landing/index.php
Labels: enhancement

#372 Code standards updates.
  htdocs/web_portal/controllers/user/view_user.php
  htdocs/web_portal/views/user/view_user.php
  lib/Gocdb_Services/Role.php
  lib/Gocdb_Services/User.php
  tests/unit/lib/Gocdb_Services/RoleServiceTest2.php
Labels: enhancement
